### ISSUE TITLE
Convert application usages of `ButtonBase` and `LinkBase`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#1050]
As of v6.2.0, the `Button` and `Link` and `IconButton` components support the styling API, obviating the need to use `ButtonBase` or `LinkBase`.

* [ ] Update usages of `ButtonBase` in `client` to use `Button` (or `IconButton`) with styling props instead
* [x] Update usages of `LinkBase` in `client` to use `Link` with styling props instead
* [x] Update usages of `ButtonBase` in `lms` to use `Button` (or `IconButton`) with styling props instead
* [x] Update usages of `LinkBase` in `lms` to use `Link` with styling props instead

This task is done when we're ready to remove `ButtonBase` and `LinkBase` from this package.

**Comment by acelaya** [comment]
I was going to tackle the lms ones, but it seems we are not using neither `LinkBase` or `ButtonBase` there.

[Grabación de pantalla desde 2023-05-25 10-37-56.webm](https://github.com/hypothesis/frontend-shared/assets/2719332/fd86e9cf-dc1a-4ecf-b5b0-db15351b0750)
