### ISSUE TITLE
Vertically stack `hyp-action` elements  instead of overflowing parent container

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/frontend-shared#118]
If not enough horizontal space is available to accommodate the elements (generally buttons) in the `hyp-action` container, stack them vertically.

![Dialogs-Hypothesis-UI-playground](https://user-images.githubusercontent.com/8555781/123425417-6a604d80-d5c2-11eb-868a-0c2f583a590c.png)

**Comment by lyzadanger** [comment]
Part of #452
