### ISSUE TITLE
Prototype and build UI for Import tab

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#1180]
We have a mockup for a new import tab in the client. We need to prototype this out and also fill in some interstitial/missing states and some messaging.

![Image](https://user-images.githubusercontent.com/439947/257886210-40d5750e-8601-4555-bf1d-57aabf6e7ea2.png)

Known state and flow details that need to be prototyped:

* If the uploaded file does not contain any valid annotations, an error message will be shown to the user
* If the uploaded file does not contain any non-duplicate annotations, a message will be shown to the user
* If the uploaded file contains valid annotations from multiple users, a dropdown of users will be rendered from which to select. If one of the users in the dropdown can be identified as the current user, it will be pre-selected.
* The drop-down should indicate the count of annotations to import for each user, and perhaps count of duplicate annotations for that user (TBD).
* If there is only one user with valid annotations to import, a message will be shown explaining this (no selection needs to be made).
* Need to provide messaging about how only top-level annotations will be imported (not replies).

Part of https://github.com/hypothesis/client/issues/5692

**Comment by acelaya** [comment]
Completed by https://github.com/hypothesis/client/pull/5710
