### ISSUE TITLE
Add bucket-bar button patterns to pattern library

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#235]
These patterns are styled in the `buttons` mixins in the client. They include the "indicator-*" patterns.

These styles are currently applied to `<button>` elements in the `Buckets` component.

**Comment by esanzgar** [comment]
Do you expect this pattern to be used in other projects apart from the client?

**Comment by lyzadanger** [comment]
> Do you expect this pattern to be used in other projects apart from the client?

Excellent question, probably not. What I'm trying to do is identify and extract all design patterns to see if any part of their underlying bits (let's say, buttons shaped like arrows, in this case, as an example) are common, and how they fit in with the rest of the design system.

This ticket might be better titled "Extract bucket-bar button patterns" as their actual implementation _might_ stay in the `client` application. Won't know 'til I get in there. The aim here is to track that some sort of examination of this pattern needs to happen.
