### ISSUE TITLE
Make it possible to "turn sizing off" for `Button`, perhaps other sized components

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#676]
Padding and spacing within buttons can be adjusted via the `size` prop, which applies some canned padding and spacing for `sm`, `md`, `lg` values, e.g. However, we have an awful lot of legacy buttons with custom or mis-matched padding and spacing.

To match current custom button styling using `Button`, it's currently necessary to either:

* Pass `!important` `classes` (e.g. `classes="!px-1.5 !py-2"`) or
* Use `ButtonBase` instead (which won't apply sizing, but also won't apply colors, etc., so you have to re-invent the wheel a bit)

One option might be to introduce an `unsized` prop similar to `ButtonBase`'s `unstyled` prop. When set, padding and spacing would not be applied. The user of `Button` could then set non-important size-related classes via `classes`.

**Comment by robertknight** [comment]
> One option might be to introduce an unsized prop similar to ButtonBase's unstyled prop. When set, padding and spacing would not be applied. 

How about an explicit `size={null}` or `size="unsized"`, to prevent a user from using an invalidation combination such as `<FooButton size="md" unstyled>`.

**Comment by lyzadanger** [comment]
> > One option might be to introduce an unsized prop similar to ButtonBase's unstyled prop. When set, padding and spacing would not be applied.
> 
> How about an explicit `size={null}` or `size="unsized"`, to prevent a user from using an invalidation combination such as `<FooButton size="md" unstyled>`.

I'm torn, as this had also occurred to me. The up-side to another `size` value is as you stated. However, it's somewhat ergonomically awkward to have to remember and manage a value of another type (e.g. `null`).

The nice thing about a Boolean value is that it is a signal that it's putting the component in a non-default state (cf. `unstyled` on `ButtonBase`), it's easy to read, and doesn't require `size` to take a value of a different type. On the other hand, as you mentioned, it would allow for the invalid combination of `size="sm" unsized`. Hmmm, stroking chin.

**Comment by lyzadanger** [comment]
I think this is part and parcel with #853 and should be given a deep think heading into v6.
