### ISSUE TITLE
Deprecate `useUniqueId`, recommending the direct use of preact's `useId` hook

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#838]
Internal hook `useUniqueId` was written before the existence of `useId` in preact. The custom hook does have a nice affordance in that it supports a prefix. Update it to use `useId` instead of a local reference for ID generation.

**Comment by acelaya** [comment]
We have discussed that we will instead deprecate `useUniqueId` and promote the use of `useId` directly.
