### ISSUE TITLE
Add `Slider` transition to library; document `TransitionComponent`s

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#966]
The `Dialog` component currently takes a `transitionComponent: TransitionComponent` prop, and the API for `TransitionComponent` is defined in exported types. The intent is that relevant components can take a `TransitionComponent`, and that this package should define, provide and document relevant transition components. As such:

* Bring the `Slider` component (in the `client`) into the package
* Document transition components in the pattern library (this may involve adding a new navigation section) and update `Dialog`'s pattern-library documentation if needed

**Comment by acelaya** [comment]
I'm thinking `transition` might be a possible group name for these new components (being `Slider` the first one).

That's how they call it in libraries like [Material UI](https://mui.com/material-ui/transitions/).

Other libraries I've checked don't have nothing specific for "transitions".
