### ISSUE TITLE
Host pattern-library independently

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/frontend-shared#973]
Find a way, any straightforward way, to deploy the pattern-library to a public URL independently of the rest of this package. This will allow us to share patterns and prototypes with a wider audience. The pattern library is getting mature enough now that this makes sense.

**Comment by acelaya** [comment]
There are a couple of options that come to my mind.

* Build a nodejs-based docker image which serves the pattern library as we do in development, using the serve-pattern-library script which uses express to serve the page.
* Build an nginx-based docker image which builds the static pattern-library assets on a first stage, and then copies them to the nginx stage.
* Build the assets, upload them to S3 and serve them via Cloudflare (like we do with the client).

The first two options have the benefit that we can incorporate the building process and deployment to other existing workflows, and then send it to Elastic Beanstalk. However, if we cannot re-use enough of the existing tooling, it might require extra infra work.

From those two, using nginx requires a bit of work on replicating express config into nginx config, but it shouldn't be super hard.

On the other hand, using express has the problem that express, mustache, etc would become a production dependency, but we don't want them to be a prod dependency of the library, so we need to find a way to "split" that.

Finally, the option about using Cloudflare comes with multi-region capabilities out of the box (something we don't have with Elastic Beanstalk, unless we put Cloudflare in front of our deployment anyway), and in theory we should also be able to reuse some deployment logic from the client.

**Comment by acelaya** [comment]
The pattern library is now available in https://patterns.hypothes.is/

**Comment by acelaya** [comment]
Closing this issue, as the pattern library is now hosted.

There are a couple of improvements and missing docs that we can do separately anyway.
